// <auto-generated />
namespace DS3Wiki.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NewTable_Weapons : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewTable_Weapons));
        
        string IMigrationMetadata.Id
        {
            get { return "202101091527222_NewTable_Weapons"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
