// <auto-generated />
namespace DS3Wiki.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NewTable_WeaponArts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewTable_WeaponArts));
        
        string IMigrationMetadata.Id
        {
            get { return "202101101627555_NewTable_WeaponArts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
